//Make some arrays of objects based on the schema design I created

//general stats
const pokedata = [
  {
    national_num: "0006",
    pokename: "Charizard",
    poketype1: "Fire",
    poketype2: "Flying",
    pokespecies: "",
    height: "0.8m",
    weight: "28.5kg",
    sign_ability: "Thick Fat",
  },
  {
    national_num: "0184",
    pokename: "Azumarill",
    poketype1: "Water",
    poketype2: "Fairy",
    pokespecies: "Aqua Rabbit",
    height: "0.8m",
    weight: "28.5kg",
    sign_ability: "Thick Fat",
  },

  {
    national_num: "0182",
    pokename: "Bellossom",
    poketype1: "Grass",
    pokespecies: "Flower",
    height: "0.4m",
    weight: "5.8kg",
    sign_ability: "Chlorophyll",
  },

  {
    national_num: "0009",
    pokename: "Blastoise",
    poketype1: "Water",
    poketype2: "N/A",
    pokespecies: "Shellfish",
    height: "1.6m",
    weight: "85.5kg",
    sign_ability: "Torrent",
  },

  {
    national_num: "0012",
    pokename: "Butterfree",
    poketype1: "Bug",
    poketype2: "Flying",
    pokespecies: "Butterfly",
    height: "1.1m",
    weight: "32kg",
    sign_ability: "Compound Eyes",
  },

  {
    national_num: "0025",
    pokename: "Pikachu",
    poketype1: "Electric",
    poketype2: "N/A",
    pokespecies: "Mouse",
    height: "0.4m",
    weight: "5.8kg",
    sign_ability: "Static",
  },
  {
    national_num: "0052",
    pokename: "Meowth",
    poketype1: "Normal",
    poketype2: "N/A",
    pokespecies: "Scratch Cat",
    height: "0.4m",
    weight: "4.2kg",
    sign_ability: "Pickup",
  },
  {
    national_num: "0094",
    pokename: "Gengar",
    poketype1: "Ghost",
    poketype2: "Poison",
    pokespecies: "Shadow",
    height: "1.5m",
    weight: "40.5kg",
    sign_ability: "Cursed Body",
  },
  {
    national_num: "0068",
    pokename: "Machamp",
    poketype1: "Fighting",
    poketype2: "N/A",
    pokespecies: "Superpower",
    height: "1.6m",
    weight: "130kg",
    sign_ability: "Guts",
  },
  {
    national_num: "0099",
    pokename: "Kingler",
    poketype1: "Water",
    poketype2: "N/A",
    pokespecies: "Pincer",
    height: "1.3m",
    weight: "60kg",
    sign_ability: "Hyper Cutter",
  },
  {
    national_num: "0131",
    pokename: "Lapras",
    poketype1: "Water",
    poketype2: "Ice",
    pokespecies: "Transport",
    height: "2.5m",
    weight: "220kg",
    sign_ability: "Water Absorb",
  },

  {
    national_num: "0133",
    pokename: "Eevee",
    poketype1: "Normal",
    poketype2: "N/A",
    pokespecies: "Evolution",
    height: "0.3m",
    weight: "6.5kg",
    sign_ability: "Run Away",
  },

  {
    national_num: "0143",
    pokename: "Snorlax",
    poketype1: "Normal",
    poketype2: "N/A",
    pokespecies: "Sleeping",
    height: "2.1m",
    weight: "460.0kg",
    sign_ability: "Immunity",
  },
  {
    national_num: "0569",
    pokename: "Garbodor",
    poketype1: "Poison",
    poketype2: "N/A",
    pokespecies: "Trash Heap",
    height: "1.9m",
    weight: "107.3kg",
    sign_ability: "Stench",
  },
  {
    national_num: "0809",
    pokename: "Melmetal",
    poketype1: "Steel",
    poketype2: "N/A",
    pokespecies: "Hex Nut",
    height: "2.5m",
    weight: "800kg",
    sign_ability: "Iron Fist",
  },
  {
    national_num: "0812",
    pokename: "Rillaboom",
    poketype1: "Grass",
    poketype2: "N/A",
    pokespecies: "Drummer",
    height: "2.1m",
    weight: "90kg",
    sign_ability: "Overgrow",
  },
  {
    national_num: "0815",
    pokename: "Cinderace",
    poketype1: "Fire",
    poketype2: "N/A",
    pokespecies: "Striker",
    height: "1.4m",
    weight: "33kg",
    sign_ability: "Blaze",
  },
  {
    national_num: "0818",
    pokename: "Inteleon",
    poketype1: "Water",
    poketype2: "N/A",
    pokespecies: "Secret Agent",
    height: "1.9m",
    weight: "45.2kg",
    sign_ability: "Torrent",
  },
  {
    national_num: "0826",
    pokename: "Orbeetle",
    poketype1: "Bug",
    poketype2: "Psychic",
    pokespecies: "Seven Spot",
    height: "0.4m",
    weight: "40.8kg",
    sign_ability: "Swarm",
  },
  {
    national_num: "0834",
    pokename: "Drednaw",
    poketype1: "Water",
    poketype2: "Rock",
    pokespecies: "Bite",
    height: "1m",
    weight: "115.5kg",
    sign_ability: "Strong Jaw",
  },
  {
    national_num: "0839",
    pokename: "Coalossal",
    poketype1: "Rock",
    poketype2: "Fire",
    pokespecies: "Coal",
    height: "2.8m",
    weight: "310.5kg",
    sign_ability: "Steam Engine",
  },
  {
    national_num: "0841",
    pokename: "Flapple",
    poketype1: "Grass",
    poketype2: "Dragon",
    pokespecies: "Apple Wing",
    height: "0.3m",
    weight: "1.0kg",
    sign_ability: "Ripen",
  },
  {
    national_num: "0842",
    pokename: "Appletun",
    poketype1: "Grass",
    poketype2: "Dragon",
    pokespecies: "Apple Nectar",
    height: "0.4m",
    weight: "13kg",
    sign_ability: "Ripen",
  },
  {
    national_num: "0844",
    pokename: "Sandaconda",
    poketype: "Ground",
    poketype2: "N/A",
    pokespecies: "Sand Snake",
    height: "3.8m",
    weight: "65.5kg",
    sign_ability: "Sand Spit",
  },
  {
    national_num: "0849",
    pokename: "Toxtricity",
    poketype1: "Electric",
    poketype2: "Poison",
    pokespecies: "Punk",
    height: "1.6m",
    weight: "40kg",
    sign_ability: "Punk Rock",
  },
  {
    national_num: "0851",
    pokename: "Centiskorch",
    poketype1: "Fire",
    poketype2: "Bug",
    pokespecies: "Radiator",
    height: "3.0m",
    weight: "120kg",
    sign_ability: "Flash Fire",
  },
  {
    national_num: "0858",
    pokename: "Hatterene",
    poketype1: "Psychic",
    poketype2: "Fairy",
    pokespecies: "Silent",
    height: "2.1m",
    weight: "5.1kg",
    sign_ability: "Healer",
  },
  {
    national_num: "0861",
    pokename: "Grimmsnarl",
    poketype1: "Dark",
    poketype2: "Fairy",
    pokespecies: "Bulk Up",
    height: "1.5m",
    weight: "61kg",
    sign_ability: "Prankster",
  },
  {
    national_num: "0879",
    pokename: "Copperajah",
    poketype: "Steel",
    poketype2: "N/A",
    pokespecies: "Copperderm",
    height: "3.0m",
    weight: "650kg",
    sign_ability: "Sheer Force",
  },
  {
    national_num: "0884",
    pokename: "Duraludon",
    poketype1: "Steel",
    poketype2: "Dragon",
    pokespecies: "Alloy",
    height: "1.8m",
    weight: "40kg",
    sign_ability: "Light Metal",
  },
  {
    national_num: "0892",
    pokename: "Urshifu",
    poketype1: "Fighting",
    poketype2: "Dark",
    pokespecies: "Wushu",
    height: "1.9m",
    weight: "105kg",
    sign_ability: "Unseen Fist",
  },
  {
    national_num: "0869",
    pokename: "Alcremie",
    poketype: "Fairy",
    poketype2: "N/A",
    pokespecies: "Cream",
    height: "0.3m",
    weight: "0.5kg",
    sign_ability: "Sweet Veil",
  },
  {
    national_num: "0132",
    pokename: "Ditto",
    poketype: "Normal",
    poketype2: "N/A",
    pokespecies: "Transform",
    height: "0.3m",
    weight: "4kg",
    sign_ability: "Limber",
  },
  {
    national_num: "0973",
    pokename: "Flamingo",
    poketype1: "Flying",
    poketype2: "Fighting",
    pokespecies: "Flower",
    height: "1.9",
    weight: "105kg",
    sign_ability: "Chlorophyll",
  },
  {
    national_num: "0823",
    pokename: "Corviknight",
    poketype1: "Flying",
    poketype2: "Steel",
    pokespecies: "Raven",
    height: "2.2m",
    weight: "75kg",
    sign_ability: "Pressure",
  },
];

//giga stats

const g_max = [
  {
    g_max_move: "Wildfire",
    pokename: "Charizard",
    g_max_move_type: "Fire",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/thumb/3/38/0006Charizard.png/100px-0006Charizard.png",
    post_g_max_image:
      "https://m.bulbapedia.bulbagarden.net/wiki/File:0006Charizard-Gigantamax.png",
    post_g_max_height: 28,
  },
  {
    g_max_move: "N/A",
    pokename: "Azumarill",
    g_max_move_type: "N/A",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/2/22/0184Azumarill.png",
    post_g_max_image: "N/A",
    post_g_max_height: 28,
  },

  {
    g_max_move: "N/A",
    pokename: "Bellossom",
    g_max_move_type: "N/A",
    b4g_max_image:
      "https://archives.bulbagarden.net/wiki/File:0182Bellossom.png",
    post_g_max_image: "N/A",
    post_g_max_height: "N/A",
  },
  {
    g_max_move: "Cannonade",
    pokename: "Blastoise",
    g_max_move_type: "Water",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/0/0a/0009Blastoise.png",
    post_g_max_image:
      "https://bulbapedia.bulbagarden.net/wiki/File:0009Blastoise-Gigantamax.png",
    post_g_max_height: 25,
  },

  {
    g_max_move: "Befuddle",
    pokename: "Butterfree",
    g_max_move_type: "Bug",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/5/55/0012Butterfree.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/e/ee/0012Butterfree-Gigantamax.png",
    post_g_max_height: 17,
  },
  {
    g_max_move: "Volt Crash",
    pokename: "Pikachu",
    g_max_move_type: "Electric",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/4/4a/0025Pikachu.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/8/8c/0025Pikachu-Gigantamax.png",
    post_g_max_height: 21,
  },
  {
    g_max_move: "Gold Rush",
    pokename: "Meowth",
    g_max_move_type: "Normal",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/d/d6/0052Meowth.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/0/08/0052Meowth-Gigantamax.png",
    post_g_max_height: 33,
  },
  {
    g_max_move: "Chi Strike",
    pokename: "Machamp",
    g_max_move_type: "Fighting",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/8/82/0068Machamp.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/e/e4/0068Machamp-Gigantamax.png",
    post_g_max_height: 25,
  },
  {
    g_max_move: "Terror",
    pokename: "Gengar",
    g_max_move_type: "Ghost",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/4/47/0094Gengar.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/4/4a/0094Gengar-Gigantamax.png",
    post_g_max_height: 20,
  },
  {
    g_max_move: "Foam Burst",
    pokename: "Kingler",
    g_max_move_type: "Water",
    b4g_max_image:
      "https://img.pokemondb.net/sprites/home/normal/kingler.png",
    post_g_max_image:
      "https://img.pokemondb.net/sprites/home/normal/kingler-gigantamax.png",
    post_g_max_height: 19,
  },
  {
    g_max_move: "Resonance",
    pokename: "Lapras",
    g_max_move_type: "Ice",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/9/99/0131Lapras.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/b/b6/0131Lapras-Gigantamax.png",
    post_g_max_height: 24,
  },
  {
    g_max_move: "Cuddle",
    pokename: "Eevee",
    g_max_move_type: "Normal",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/e/e2/0133Eevee-Gigantamax.png",
    b4g_max_image:
      "https://bulbapedia.bulbagarden.net/wiki/File:0133Eevee.png",
    post_g_max_height: 18,
  },
  {
    g_max_move: "Replenish",
    pokename: "Snorlax",
    g_max_move_type: "Normal",
    b4g_max_image:
      "https://img.pokemondb.net/sprites/home/normal/snorlax.png",
    post_g_max_image:
      "https://img.pokemondb.net/sprites/home/normal/snorlax-gigantamax.png",
    post_g_max_height: 35,
  },
  {
    g_max_move: "Malodor",
    pokename: "Garbodor",
    g_max_move_type: "Poison",
    b4g_max_image:
      '<img src=<img src="https://img.pokemondb.net/sprites/home/shiny/garbodor.png" alt="Garbodor"/>',
    post_g_max_image:
      '<img src=<img src="https://img.pokemondb.net/sprites/home/shiny/garbodor-gigantamax.png" alt="Garbodor"/>',
    post_g_max_height: 21,
  },
  {
    g_max_move: "Meltdown",
    pokename: "Melmetal",
    g_max_move_type: "Steel",
    b4g_max_image:
      "https://bulbapedia.bulbagarden.net/wiki/File:0809Melmetal.png",
    post_g_max_image:
      "https://bulbapedia.bulbagarden.net/wiki/File:0809Melmetal-Gigantamax.png",
    post_g_max_height: 25,
  },
  {
    g_max_move: "Drum Solo",
    pokename: "Rillaboom",
    g_max_move_type: "Grass",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/3/38/0812Rillaboom.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/3/38/0812Rillaboom-Gigantamax.png",
    post_g_max_height: 28,
  },
  {
    g_max_move: "Fireball",
    pokename: "Cinderace",
    g_max_move_type: "Fire",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/6/61/0815Cinderace.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/7/78/0815Cinderace-Gigantamax.png",
    post_g_max_height: 27,
  },
  {
    g_max_move: "Hydrosnipe",
    pokename: "Inteleon",
    g_max_move_type: "Water",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/d/dc/0818Inteleon.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/2/29/0818Inteleon-Gigantamax.png",
    post_g_max_height: 40,
  },
  {
    g_max_move: "Wind Rage",
    pokename: "Corviknight",
    g_max_move_type: "Flying",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/c/c2/0823Corviknight.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/5/55/0823Corviknight-Gigantamax.png",
    post_g_max_height: 14,
  },
  {
    g_max_move: "Gravitas",
    pokename: "Orbeetle",
    g_max_move_type: "Psychic",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/5/57/0826Orbeetle.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/d/d5/0826Orbeetle-Gigantamax.png",
    post_g_max_height: 14,
  },
  {
    g_max_move: "Stonesurge",
    pokename: "Drednaw",
    g_max_move_type: "Water",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/8/82/0834Drednaw.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/a/a2/0834Drednaw-Gigantamax.png",
    post_g_max_height: 24,
  },
  {
    g_max_move: "Volcalith",
    pokename: "Coalossal",
    g_max_move_type: "Rock",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/c/c4/0839Coalossal.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/1/10/0839Coalossal-Gigantamax.png",
    post_g_max_height: 42,
  },
  {
    g_max_move: "Tartness",
    pokename: "Flapple",
    g_max_move_type: "Grass",
    b4g_max_image:
      "https://img.pokemondb.net/sprites/home/shiny/flapple.png",
    post_g_max_image:
      "https://img.pokemondb.net/sprites/home/shiny/flapple-gigantamax.png",
    post_g_max_height: 17,
  },
  {
    g_max_move: "Sweetness",
    pokename: "Appletun",
    g_max_move_type: "Grass",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/f/fe/0842Appletun.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/4/42/0841Flapple-Gigantamax.png",
    post_g_max_height: 17,
  },
  {
    g_max_move: "Sandblast",
    pokename: "Sandaconda",
    g_max_move_type: "Ground",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/b/b9/0844Sandaconda.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/f/fc/0844Sandaconda-Gigantamax.png",
    post_g_max_height: 22,
  },
  {
    g_max_move: "Stun Shock",
    pokename: "Toxtricity",
    g_max_move_type: "Electric",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/0/00/0849Toxtricity-Amped.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/d/de/0849Toxtricity-Gigantamax.png",
    post_g_max_height: 24,
  },
  {
    g_max_move: "Centiferno",
    pokename: "Centiskorch",
    g_max_move_type: "Fire",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/8/83/0851Centiskorch.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/3/3c/0851Centiskorch-Gigantamax.png",
    post_g_max_height: 75,
  },
  {
    g_max_move: "Smite",
    pokename: "Hatterene",
    g_max_move_type: "Fairy",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/1/19/0858Hatterene.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/1/10/0858Hatterene-Gigantamax.png",
    post_g_max_height: 26,
  },
  {
    g_max_move: "Snooze",
    pokename: "Grimmsnarl",
    g_max_move_type: "Dark",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/2/2d/0861Grimmsnarl.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/d/df/0861Grimmsnarl-Gigantamax.png",
    post_g_max_height: 17,
  },
  {
    g_max_move: "Finale",
    pokename: "Alcremie",
    g_max_move_type: "Fairy",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/8/81/0869Alcremie.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/9/93/0869Alcremie-Gigantamax.png",
    post_g_max_height: 30,
  },
  {
    g_max_move: "Steelsurge",
    pokename: "Copperajah",
    g_max_move_type: "Steel",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/a/a3/0879Copperajah.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/1/19/0879Copperajah-Gigantamax.png",
    post_g_max_height: 23,
  },
  {
    g_max_move: "Depletion",
    pokename: "Duraludon",
    g_max_move_type: "Dragon",
    b4g_max_image:
      "https://archives.bulbagarden.net/media/upload/f/f4/0884Duraludon.png",
    post_g_max_image:
      "https://archives.bulbagarden.net/media/upload/d/d4/0884Duraludon-Gigantamax.png",
    post_g_max_height: 43,
  },
  {
    g_max_move: "Rapid Flow",
    pokename: "Urshifu",
    g_max_move_type: "Dark",
    b4g_max_image:
      "https://bulbapedia.bulbagarden.net/wiki/File:0892Urshifu-Single_Strike.png",
    post_g_max_image:
      "https://bulbapedia.bulbagarden.net/wiki/File:0892Urshifu-Gigantamax_Single_Strike.png",
    post_g_max_height: 26,
  },
];
//egg types
const egg_groups = [
  { pokename: "Gengar", egg_group: "Amorphous" },
  { pokename: "Butterfree", egg_group: "Bug" },
  { pokename: "Bagon", egg_group: "Dragon" },
  { pokename: "Alcremie", egg_group: "Fairy" },
  { pokename: "Pikachu", egg_group: "Field" },
  { pokename: "Flamingo", egg_group: "Flying" },
  { pokename: "Bellossom", egg_group: "Grass" },
  { pokename: "Kirlia", egg_group: "Human-Like" },
  { pokename: "Coalossal", egg_group: "Mineral" },
  { pokename: "Snorlax", egg_group: "Monster" },
  { pokename: "Squirtle", egg_group: "Water 1" },
  { pokename: "Tatsugiri", egg_group: "Water 2" },
  { pokename: "Kingler", egg_group: "Water 3" },
  { pokename: "Ditto", egg_group: "Ditto" },
  { pokename: "Melmetal", egg_group: "Undiscovered" },
];

const poketype_egg = [
  { pokename: "Butterfree", poketype: "Bug", egg_group: "Bug" },
  { pokename: "Grimmsnarl", poketype: "Dark", egg_group: "Fairy" },
  { pokename: "Duraludon", poketype: "Dragon", egg_group: "Mineral" },
  { pokename: "Pikachu", poketype: "Electric", egg_group: "Fairy" },
  { pokename: "Alcremie", poketype: "Fairy", egg_group: "Amorphous" },
  { pokename: "Machamp", poketype: "Fighting", egg_group: "Human-Like" },
  { pokename: "Centiskorch", poketype: "Fire", egg_group: "Bug" },
  { pokename: "Flamingo", poketype: "Flying", egg_group: "Flying" },
  { pokename: "Bellossom", poketype: "Grass", egg_group: "Grass" },
  { pokename: "Sandaconda", poketype: "Ground", egg_group: "Field" },
  { pokename: "Lapras", poketype: "Ice", egg_group: "Water 1" },
  { pokename: "Meowth", poketype: "Normal", egg_group: "Field" },
  { pokename: "Hatterene", poketype: "Psychic", egg_group: "Fairy" },
  { pokename: "Garbodor", poketype: "Poison", egg_group: "Mineral" },
  { pokename: "Coalossal", poketype: "Rock", egg_group: "Mineral" },
  { pokename: "Copperajah", poketype: "Steel", egg_group: "Field" },
  { pokename: "Drednaw", poketype: "Water", egg_group: "Monster" },
  { pokename: "Gengar", poketype: "Ghost", egg_group: "Amorphous" },
  { pokename: "Melmetal", poketype: "Steel", egg_group: "Undiscovered" },
];

//breeding
const breeding = [
  {
    breeding_id: "0182-G",
    pokename: "Bellossom",
    egg_group1: "Grass",
    egg_group2: "",
    gender: "50% male, 50% female",
    comp_parent: "Villeplume",
  },
  {
    breeding_id: "0045-G",
    pokename: "Vileplume",
    egg_group1: "Grass",
    egg_group2: "N/A",
    gender: "50% male, 50% female",
    comp_parent: "Bellossom",
  },
  {
    breeding_id: "0007-W1M",
    pokename: "Squirtle",
    egg_group1: "Water 1",
    egg_group2: "Monster",
    gender: "87.5% male, 12.5% female",
    comp_parent: "Ludicolo",
  },
  {
    breeding_id: "0869-AF",
    pokename: "Alcremie",
    egg_group1: "Amorphous",
    egg_group2: "Fairy",
    gender: "100% female",
    comp_parent: "Mimikyu",
  },
  {
    breeding_id: "0296-H-L",
    pokename: "Makuhita",
    egg_group1: "Human-like",
    egg_group2: "N/A",
    gender: "75% male, 25% female",
    comp_parent: "Hawlucha",
  },
  {
    breeding_id: "0281-AH-L",
    pokename: "Kirlia",
    egg_group1: "Amorphous",
    egg_group2: "Human-like",
    gender: "50% male, 50% female",
    comp_parent: "Gengar",
  },
  {
    breeding_id: "0778-A",
    pokename: "Mimikyu",
    egg_group1: "Amorphous",
    egg_group2: "N/A",
    gender: "50% male, 50% female",
    comp_parent: "Gengar, Kirlia",
  },
  {
    breeding_id: "0094-A",
    pokename: "Gengar",
    egg_group1: "Amorphous",
    egg_group2: "N/A",
    gender: "50% male, 50% female",
    comp_parent: "Gallade",
  },
  {
    breeding_id: "0842-DG",
    pokename: "Appletun",
    egg_group1: "Dragon",
    egg_group2: "Grass",
    gender: "50% male, 50% female",
    comp_parent: "Sprigatito",
  },
  {
    breeding_id: "0025-FAFI",
    pokename: "Pikachu",
    egg_group1: "Field",
    egg_group2: "Fairy",
    gender: "50% male, 50% female",
    comp_parent: "Pachirisu",
  },

  {
    breeding_id: "0052-FI",
    pokename: "Meowth",
    egg_group1: "Field",
    egg_group2: "N/A",
    gender: "50% male, 50% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0068-H-L",
    pokename: "Machamp",
    egg_group1: "Human-like",
    egg_group2: "N/A",
    gender: "75% male, 25% female",
    comp_parent: "Makuhita",
  },
  {
    breeding_id: "0841-DG",
    pokename: "Flapple",
    egg_group1: "Dragon",
    egg_group2: "Grass",
    gender: "50% male, 50% female",
    comp_parent: "Bagon",
  },
  {
    breeding_id: "0858-FA",
    pokename: "Hatterene",
    egg_group1: "Fairy",
    egg_group2: "N/A",
    gender: "100% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "00861-FAH-L",
    pokename: "Grimmsnarl",
    egg_group1: "Fairy",
    egg_group2: "Human-like",
    gender: "100% male",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0879-FIM",
    pokename: "Copperajah",
    egg_group1: "Field",
    egg_group2: "Mineral",
    gender: "50% male, 50% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0892-U",
    pokename: "Urshifu",
    egg_group1: "Undiscovered",
    egg_group2: "No Eggs",
    gender: "87.5% male, 12.5% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0143-M",
    pokename: "Snorlax",
    egg_group1: "Monster",
    egg_group2: "N/A",
    gender: "87.5% male, 12.5% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0099-W3",
    pokename: "Kingler",
    egg_group1: "Water 3",
    egg_group2: "",
    gender: "50% male, 50% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0569-M",
    pokename: "Garbodor",
    egg_group1: "Mineral",
    egg_group2: "N/A",
    gender: "50% male, 50% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0133-FI",
    pokename: "Eevee",
    egg_group1: "Field",
    egg_group2: "N/A",
    gender: "87.5% male, 12.5% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0809-U",
    pokename: "Melmetal",
    egg_group: "No Eggs Discovered",
    egg_group2: "N/A",
    gender: "Gender Unknown",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0812-FIG",
    pokename: "Rillaboom",
    egg_group1: "Field",
    egg_group2: "Grass",
    gender: "87.5% male, 12.5% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0815-FIH-L",
    pokename: "Cinderace",
    egg_group1: "Field",
    egg_group2: "Human-Like",
    gender: "87.5% male, 12.5% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0818-W1FI",
    pokename: "Inteleon",
    egg_group1: "Water 1",
    egg_group2: "Field",
    gender: "87.5% male, 12.5% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0823-FL",
    pokename: "Corviknight",
    egg_group1: "Flying",
    egg_group2: "N/A",
    gender: "50% male, 50% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0826-B",
    pokename: "Orbeetle",
    egg_group1: "Bug",
    egg_group2: "N/A",
    gender: "50% male, 50% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0834-MW1",
    pokename: "Drednaw",
    egg_group1: "Monster",
    egg_group2: "Water1",
    gender: "50% male, 50% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0839-M",
    pokename: "Coalossal",
    egg_group: "Mineral",
    egg_group2: "N/A",
    gender: "50% male, 50% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0844-FID",
    pokename: "Sandaconda",
    egg_group1: "Field",
    egg_group2: "Dragon",
    gender: "50% male, 50% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0849-H-L",
    pokename: "Toxtricity",
    egg_group: "Human-Like",
    egg_group2: "N/A",
    gender: "50% male, 50% female",
    comp_parent: "Pachirisu",
  },
  {
    breeding_id: "0851-B",
    pokename: "Centiskorch",
    egg_group: "Bug",
    egg_group2: "N/A",
    gender: "50% male, 50% female",
    comp_parent: "Pachirisu",
  },
];

//pokemon

module.exports = { pokedata, g_max, egg_groups, poketype_egg, breeding };
